
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("Dummy6.Resource", IsApplication=true)>]
    do ()

namespace TestFSAndroid
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnExceptione37fe5c84bb1429bb0c63513cee5f09e of obj
    exception ReturnNoneExceptione37fe5c84bb1429bb0c63513cee5f09e
    [<AutoOpen>]
    module FuncConvertFinalOverloade37fe5c84bb1429bb0c63513cee5f09e =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                ()


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member Icon = 2130837504
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050000
            static member HelloWorldButton = 2131034112
            
            // aapt resource value: 0x7f050001
            static member TestCheckBox = 2131034113
            
            // aapt resource value: 0x7f050002
            static member WifiAvailability = 2131034114
            
            // aapt resource value: 0x7f050003
            static member scale1 = 2131034115
            
            // aapt resource value: 0x7f050004
            static member scale1_1 = 2131034116
            
            // aapt resource value: 0x7f05000d
            static member scale1_10 = 2131034125
            
            // aapt resource value: 0x7f050005
            static member scale1_2 = 2131034117
            
            // aapt resource value: 0x7f050006
            static member scale1_3 = 2131034118
            
            // aapt resource value: 0x7f050007
            static member scale1_4 = 2131034119
            
            // aapt resource value: 0x7f050008
            static member scale1_5 = 2131034120
            
            // aapt resource value: 0x7f050009
            static member scale1_6 = 2131034121
            
            // aapt resource value: 0x7f05000a
            static member scale1_7 = 2131034122
            
            // aapt resource value: 0x7f05000b
            static member scale1_8 = 2131034123
            
            // aapt resource value: 0x7f05000c
            static member scale1_9 = 2131034124
            
            // aapt resource value: 0x7f05000e
            static member scale2 = 2131034126
            
            // aapt resource value: 0x7f05000f
            static member scale2_1 = 2131034127
            
            // aapt resource value: 0x7f050018
            static member scale2_10 = 2131034136
            
            // aapt resource value: 0x7f050010
            static member scale2_2 = 2131034128
            
            // aapt resource value: 0x7f050011
            static member scale2_3 = 2131034129
            
            // aapt resource value: 0x7f050012
            static member scale2_4 = 2131034130
            
            // aapt resource value: 0x7f050013
            static member scale2_5 = 2131034131
            
            // aapt resource value: 0x7f050014
            static member scale2_6 = 2131034132
            
            // aapt resource value: 0x7f050015
            static member scale2_7 = 2131034133
            
            // aapt resource value: 0x7f050016
            static member scale2_8 = 2131034134
            
            // aapt resource value: 0x7f050017
            static member scale2_9 = 2131034135
            
            // aapt resource value: 0x7f050019
            static member scale3 = 2131034137
            
            // aapt resource value: 0x7f05001a
            static member scale3_1 = 2131034138
            
            // aapt resource value: 0x7f050023
            static member scale3_10 = 2131034147
            
            // aapt resource value: 0x7f05001b
            static member scale3_2 = 2131034139
            
            // aapt resource value: 0x7f05001c
            static member scale3_3 = 2131034140
            
            // aapt resource value: 0x7f05001d
            static member scale3_4 = 2131034141
            
            // aapt resource value: 0x7f05001e
            static member scale3_5 = 2131034142
            
            // aapt resource value: 0x7f05001f
            static member scale3_6 = 2131034143
            
            // aapt resource value: 0x7f050020
            static member scale3_7 = 2131034144
            
            // aapt resource value: 0x7f050021
            static member scale3_8 = 2131034145
            
            // aapt resource value: 0x7f050022
            static member scale3_9 = 2131034146
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member Main = 2130903040
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040001
            static member app_name = 2130968577
            
            // aapt resource value: 0x7f040006
            static member disable_message = 2130968582
            
            // aapt resource value: 0x7f040005
            static member enable_message = 2130968581
            
            // aapt resource value: 0x7f040000
            static member hello = 2130968576
            
            // aapt resource value: 0x7f040003
            static member wifi_available = 2130968579
            
            // aapt resource value: 0x7f040002
            static member wifi_state = 2130968578
            
            // aapt resource value: 0x7f040004
            static member wifi_unavailable = 2130968580
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

